# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=False),
        ),
    ]
