# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
