# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=11, unique=True),
            preserve_default=False,
        ),
    ]
