# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comingsoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False, verbose_name='Coming Soon Mode')),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Coming Soon',
                'verbose_name': 'Coming Soon',
            },
        ),
        migrations.CreateModel(
            name='IgnoreURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200)),
                ('about', models.CharField(help_text='About this URL', max_length=100)),
                ('comingsoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comingsoon.Comingsoon')),
            ],
        ),
    ]
